export let hourData = [
    { hour: '00', amount: 0 },
    { hour: '01', amount: 0 },
    { hour: '02', amount: 0 },
    { hour: '03', amount: 0 },
    { hour: '04', amount: 0 },
    { hour: '05', amount: 0 },
    { hour: '06', amount: 0 },
    { hour: '07', amount: 0 },
    { hour: '08', amount: 0 },
    { hour: '09', amount: 0 },
    { hour: '10', amount: 0 },
    { hour: '11', amount: 0 },
    { hour: '12', amount: 0 },
    { hour: '13', amount: 0 },
    { hour: '14', amount: 0 },
    { hour: '15', amount: 0 },
    { hour: '16', amount: 0 },
    { hour: '17', amount: 0 },
    { hour: '18', amount: 0 },
    { hour: '19', amount: 0 },
    { hour: '20', amount: 0 },
    { hour: '21', amount: 0 },
    { hour: '22', amount: 0 },
    { hour: '24', amount: 0 }
  ];
  